### ISSUE TITLE
Can you hook this? Is it okay, you can think about it.

### ISSUE THREAD

**Issue by Cqmmls** [MagicTeaMC/CatchBall#38]
https://github.com/Xyness/SimpleClaimSystem

**Comment by MagicTeaMC** [comment]
I can't find any API usage of this plugin, but I will try it when I'm free

**Comment by MagicTeaMC** [comment]
I'm waiting for an API to support it (https://github.com/Xyness/SimpleClaimSystem/issues/7)

**Comment by MagicTeaMC** [comment]
[CatchBall-1.2.4.jar.zip](https://github.com/user-attachments/files/16245392/CatchBall-1.2.4.jar.zip) (You need to unzip it)
This build must work with SimpleClaimSystem 1.10.0.2, sorry for late
